export interface Organization {
  id: string;
  organizationName: string;
  organizationType: 'Private' | 'Trust' | 'Government';
  registrationNumber: string;
  gst: string;
  address: string;
  city: string;
  state: string;
  country: string;
  pincode: string;
  contactNumber: string;
  email: string;
  timeZone: string;
  organizationUrl: string;
  institutionUrlSame: boolean;
  softwareWebsiteUrl: string;
  loginTemplate: string;
  logo: string;
  defaultLanguage: string;
  adminName: string;
  adminEmail: string;
  adminMobile: string;
  status: 'Active' | 'Inactive';
  mouCopy: string;
  poNumber: string;
  poStartDate: string;
  poEndDate: string;
  subscriptionPlan: 'Basic' | 'Standard' | 'Premium';
  enabledModules: string[];
  invoiceType: string;
  invoiceFrequency: string;
  paymentMode: string;
  invoiceAmount: string;
  paymentStatus: 'Pending' | 'Partial' | 'Paid';
  paymentReceived: boolean;
  paymentDate: string;
  transactionReference: string;
  pocName: string;
  pocEmail: string;
  pocContact: string;
  supportSLA: string;
}
